#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# Called by bazel-contrib/release_ruleset build job.
# $1 = tag name (e.g., 5.3.0-bcr.3)
# stdout = release notes (captured to release_notes.txt by the workflow)

TAG="${1:?usage: release_prep.sh TAG}"

# Extract the upstream jemalloc version from the fork's tag.
# 5.3.0-bcr.3 -> 5.3.0
UPSTREAM="${TAG%%-bcr.*}"

echo "::group::Verify source against upstream ${UPSTREAM}"

# Download the official upstream release tarball (immutable release asset).
UPSTREAM_URL="https://github.com/jemalloc/jemalloc/releases/download/${UPSTREAM}/jemalloc-${UPSTREAM}.tar.bz2"
echo "Downloading ${UPSTREAM_URL}"
curl --fail --silent --show-error --location -o upstream.tar.bz2 "${UPSTREAM_URL}"

# Extract upstream source.
tar xjf upstream.tar.bz2

# Apply all patches from .github/patches/ to the extracted upstream source.
# These patches are the complete, explicit record of intentional modifications.
if compgen -G ".github/patches/*.patch" > /dev/null; then
  for patch in .github/patches/*.patch; do
    echo "Applying patch: ${patch}"
    patch --no-backup-if-mismatch -d "jemalloc-${UPSTREAM}" -p1 < "${patch}"
  done
fi

# Verify: diff the patched upstream against the fork's source tree.
# We only care about content differences in files that exist in both trees.
# "Only in" upstream = generated files in the release tarball (configure, docs, VERSION) — expected.
# "Only in" fork = Bazel additions — handled by --exclude flags.
echo "Diffing patched upstream against fork source..."
FULL_DIFF=$(diff -r "jemalloc-${UPSTREAM}" . \
  --exclude='.git' \
  --exclude='.github' \
  --exclude='.bcr' \
  --exclude='.bazelrc' \
  --exclude='.bazelversion' \
  --exclude='.bazelignore' \
  --exclude='.gitattributes' \
  --exclude='.gitignore' \
  --exclude='BUILD.bazel' \
  --exclude='MODULE.bazel' \
  --exclude='MODULE.bazel.lock' \
  --exclude='*.bzl' \
  --exclude='jemalloc_hdr_gen.cc' \
  --exclude='README.md' \
  --exclude='settings' \
  --exclude='tools' \
  --exclude='examples' \
  --exclude='specs' \
  --exclude='bazel-*' \
  --exclude='upstream.tar.bz2' \
  --exclude="jemalloc-${UPSTREAM}" \
  || true)

# Filter out upstream-only files (generated by autoconf: configure, docs, VERSION).
# These exist in the upstream tarball but not in the fork's git tree — expected.
# Keep fork-only "Only in ." lines — these would indicate unexpected additions
# not covered by the --exclude list.
CONTENT_DIFFS=$(echo "${FULL_DIFF}" | grep -v "^Only in jemalloc-${UPSTREAM}" || true)

if [ -n "${CONTENT_DIFFS}" ]; then
  echo "::error::Source verification failed. Fork source differs from patched upstream:"
  echo "${FULL_DIFF}"
  exit 1
fi

echo "Source verification passed."
echo "::endgroup::"

# Create the release tarball. .gitattributes export-ignore rules control exclusions.
ARCHIVE="jemalloc-${TAG}.tar.gz"
git archive --format=tar.gz --prefix="jemalloc-${TAG}/" HEAD -o "${ARCHIVE}"
echo "Created ${ARCHIVE}"

# Output release notes to stdout.
cat <<EOF
## jemalloc ${TAG}

Bazel build of [jemalloc ${UPSTREAM}](https://github.com/jemalloc/jemalloc/releases/tag/${UPSTREAM}).

### Installation

\`\`\`starlark
bazel_dep(name = "jemalloc", version = "${TAG}")
\`\`\`

### Source verification

This release includes a [SLSA provenance attestation](https://slsa.dev/) linking the
tarball to the workflow run that produced it. The workflow verified that the fork's C
source is identical to the [official upstream tarball](${UPSTREAM_URL}) with only
[documented patches](.github/patches/).

Verify with:
\`\`\`
gh attestation verify jemalloc-${TAG}.tar.gz --repo sallustfire/jemalloc
\`\`\`
EOF
